### ISSUE TITLE
Yellow or Blue for neutral?

### ISSUE THREAD

**Issue by namnatulco** [UlmApi/mahlowat#1]
On `/result.php#detail`, some places show blue for neutral answers, and some places (explanations) show yellow. This should be made consistent (thanks @hkopp for reporting).

**Comment by stkdiretto** [comment]
Agree. I'd be okay with the yellow – the tree as a symbol irks me more than the color ;)

**Comment by stkdiretto** [comment]
Nope, there's still instances where yellow is used – e.g., in the question numbers while clicking through the form, and in the detailed result page. I'm not quite happy with the blue, anyway :/

Suggestion: Revert all the neutral colours to that gary yellow (or find another color?), but replace that strange tree w/ glyphicon-record or glyphicon-option-horizontal or glyphicon-asterisk?

**Comment by namnatulco** [comment]
The revert is what I tried to do, but obviously it didn't work. However, I just checked, and it looks like the reason might be that I didn't deploy the code :-).  However, I also forgot to change `btn-info` to `btn-warning` at some point (why are we (ab)using those CSS styles anyway...?). That's fixed now.

**Comment by stkdiretto** [comment]
results.php :D

**Comment by namnatulco** [comment]
d'oh.

**Comment by namnatulco** [comment]
For completeness' sake,  ce5f0e9b.
